// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiSKf0ARTGfWvKeApt60GGt5cvqXvXEkM',
    appId: '1:934812301533:android:352d3000a7bfe55bd80334',
    messagingSenderId: '934812301533',
    projectId: 'records-a819b',
    databaseURL: 'https://records-a819b-default-rtdb.firebaseio.com',
    storageBucket: 'records-a819b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWZbqkV9AAMLQXprkSNH597rKb3dWvFUU',
    appId: '1:934812301533:ios:345a2450cefaf363d80334',
    messagingSenderId: '934812301533',
    projectId: 'records-a819b',
    databaseURL: 'https://records-a819b-default-rtdb.firebaseio.com',
    storageBucket: 'records-a819b.appspot.com',
    iosClientId: '934812301533-pikrgtkv9ddjtlunuhfdpmihu7b4gi0r.apps.googleusercontent.com',
    iosBundleId: 'com.example.yazilar',
  );
}
