// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC71kU4l-wHoXGI85WFBgvCDDr7eFyX-Ng',
    appId: '1:771758996554:web:b565c412444c95c26c7ab3',
    messagingSenderId: '771758996554',
    projectId: 'flutter-articles-c10ce',
    authDomain: 'flutter-articles-c10ce.firebaseapp.com',
    storageBucket: 'flutter-articles-c10ce.appspot.com',
    measurementId: 'G-Q3HKJ0H5YN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGFv8t1fdvK9Q3sm7_oP8WVwF-vyCDKE0',
    appId: '1:771758996554:android:ac27ae7d80d595ed6c7ab3',
    messagingSenderId: '771758996554',
    projectId: 'flutter-articles-c10ce',
    storageBucket: 'flutter-articles-c10ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAydUeejd7iFYx1DXoyjyjgf1YVX4mKC-8',
    appId: '1:771758996554:ios:42c4544b132aa3936c7ab3',
    messagingSenderId: '771758996554',
    projectId: 'flutter-articles-c10ce',
    storageBucket: 'flutter-articles-c10ce.appspot.com',
    iosClientId: '771758996554-6008uv58tp85trg9b9o1cap9dddr3k1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.yazilar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAydUeejd7iFYx1DXoyjyjgf1YVX4mKC-8',
    appId: '1:771758996554:ios:42c4544b132aa3936c7ab3',
    messagingSenderId: '771758996554',
    projectId: 'flutter-articles-c10ce',
    storageBucket: 'flutter-articles-c10ce.appspot.com',
    iosClientId: '771758996554-6008uv58tp85trg9b9o1cap9dddr3k1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.yazilar',
  );
}
